name: Staging Deploy 🚀
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: f-dev
    environment:
      name: "staging"
      url: http://devdat-api.fikrifirmanf.com/
    steps:
      - uses: actions/checkout@v3
      - name: Docker compose build
        run: sudo docker compose up --build -d
